export const scenarios = [
  {
    id: "bugfix",
    title: "不具合を再現して修正を確かめる",
    description: "設定が保存されない不具合を担当。再現条件を伝え、テストとレビューで確認します。",
    ids: ["prompt-18", "prompt-20", "workflow-01"],
    steps: ["再現条件を伝える", "テストの範囲を決める", "変更をレビューする"],
  },
  {
    id: "onboarding",
    title: "初めてのリポジトリで作業する",
    description: "引き継いだプロジェクトを調べ、チームの規則と権限を確認してから作業します。",
    ids: ["prompt-19", "agents-01", "safe-01"],
    steps: ["処理の流れを調べる", "チームの規則を確認する", "承認とアクセス範囲を区別する"],
  },
  {
    id: "parallel",
    title: "作業を分けて変更を受け渡す",
    description: "手元の作業を保ちながら別の修正を進め、開始状態と受け渡し方法を選びます。",
    ids: ["workflow-03", "workflow-25", "workflow-05"],
    steps: ["作業場所を分ける", "引き継ぐ変更を選ぶ", "手元へ受け渡す"],
  },
  {
    id: "ci-output",
    title: "CIでCodexの結果を自動処理する",
    description: "対話なしで調査を実行し、進行状況を追跡して、最終結果を後続ジョブへ渡します。",
    ids: ["basic-04", "basic-12", "basic-13"],
    steps: ["非対話で実行する", "実行イベントを読み取る", "最終結果の形式を決める"],
  },
  {
    id: "hook-checks",
    title: "Hookで実行前後を検査する",
    description: "チームの検査Hookを更新。定義を確認し、危険な操作の事前検査と実行結果の確認を分けます。",
    ids: ["extend-12", "extend-13", "extend-14"],
    steps: ["変更した定義を確認する", "実行前に検査する", "実行後の結果を確認する"],
  },
  {
    id: "safe-permissions",
    title: "権限を広げすぎずに作業を進める",
    description:
      "ローカルの修正中に共有テストデータの更新が必要になりました。作業範囲と承認を設定し、必要な場所だけを追加します。",
    ids: ["safe-09", "safe-07", "safe-04"],
    steps: ["編集できる範囲を決める", "境界を越える前に確認する", "必要なフォルダーだけ追加する"],
  },
  {
    id: "session-recovery",
    title: "中断した会話を探して作業を切り替える",
    description: "昨日の調査を再開し、別案は元の履歴を残して検討。別の課題に移る時は会話を新しくします。",
    ids: ["session-21", "session-24", "session-25"],
    steps: ["見つからない会話を探す", "元の履歴を残して分岐する", "別の課題を新しい会話で始める"],
  },
  {
    id: "instruction-recovery",
    title: "チームの指示が反映されない原因を調べる",
    description: "支払いサービスでテスト規則が反映されません。読み込み元と優先順位を調べ、修正後に読み直します。",
    ids: ["agents-10", "agents-15", "agents-04"],
    steps: ["対象フォルダーで読み込み元を確認する", "同じ階層の優先ファイルを調べる", "修正した指示を読み直す"],
  },
  {
    id: "scheduled-operations",
    title: "定期タスクを安全に運用する",
    description: "毎朝のコード点検を自動化。依頼を試運転し、手元の変更と分離して、予定時刻の実行条件を確認します。",
    ids: ["workflow-12", "workflow-10", "surfaces-07"],
    steps: ["定期化する前に試運転する", "手元の作業と分離する", "実行時の端末とアプリを確認する"],
  },
  {
    id: "cloud-recovery",
    title: "Cloud環境の設定と依存関係を切り分ける",
    description: "Cloudでテストが動きません。消えた環境変数、秘密情報の利用範囲、古い依存関係を順に調べます。",
    ids: ["surfaces-18", "surfaces-03", "surfaces-19"],
    steps: ["環境変数の引き継ぎを確認する", "秘密情報を使える段階を確認する", "キャッシュした依存関係を更新する"],
  },
] as const;
